home-work-22
Karolina777/robotdreams-python pull request #15
Opened 2023-05-08 19:14 UTC by Karolina777

please, review my homework

2023-05-11 13:09 UTC, klymenok requested changes

2023-05-11 13:09 UTC, klymenok commented on 22/hmw-22-04
> +SELECT users.id, users.first_name, users.last_name, total_purchases
Запит працює некоректно, відображаючи однакову суму покупок для кожного запису. 
Для коректного виводу даних можна зробити запит даних з таблиці purchase, додати до цих дани дані із таблиць users та books, згрупувати дані по users.id та порахувати суму books.price:
```
select users.id, users.first_name, users.last_name, sum(books.price) from purchase join books on purchase.book_id = books.id join users on purchase.user_id = users.id group by users.id
```

2023-05-13 13:18 UTC, Karolina777 commented on 22/hmw-22-04
> +SELECT users.id, users.first_name, users.last_name, total_purchases
дякую, виправила

2023-05-17 16:06 UTC, klymenok approved these changes

2023-05-19 17:55 UTC, merged