homework 12
Karolina777/robotdreams-python pull request #8
Opened 2023-04-09 19:12 UTC by Karolina777

Please, review my home task for the 12th class

2023-04-10 13:05 UTC, klymenok requested changes

2023-04-10 13:05 UTC, klymenok commented on 12/hmw-12-01.py
> +if os.path.isfile(file_path):
Читання і перезапис файлу мають бути інтегровані в роботу вашої телефонної книги. Алгоритм приблизно наступний:
1. При запуску програми ви перевіряєте чи існує файл і читаєте дані з нього, записуючи їх у вже звичний dict. 
2. Телефонна книга працює із dict, так як вона була реалізована попереднього разу
3. При здійсненні операцій, що змінюють структуру телефонної книги (створення чи видалення запису), вам потрібно перезаписати файл.

2023-04-10 13:05 UTC, klymenok commented on 12/hmw-12-01.py
> +    match command_length:
Також, вам потрібно взяти той самий код, що і у завданні 07, тільки модифікувати його, додавши читання і запис в файл. В цьому коді не вистачає значної частини із того, що є в виконанні ДЗ 07

2023-04-10 13:05 UTC, klymenok commented on 12/hmw-12-02.py
> +        with open("hmw-12-02-file_name.txt" , "w") as f:
Дані тут будуть постійно перезаписуватися. Для того, щоб вести журнал подій, краще додавати дані до вже існуючих ("a")

2023-04-10 20:04 UTC, Karolina777 commented
Hi, I've made the changes you suggested.
In the 1st task, I added the code from homework-7, but only the part that actually works with the phone book, and omitted the code needed in homework-7 to create the initial phone book. I believe we don't need this part here as we read the initial phonebook from the file. Thank you!

2023-04-11 20:46 UTC, klymenok requested changes

2023-04-11 20:46 UTC, klymenok commented on 12/hmw-12-01.py
> +if initial_records != len(phone_book):
перезапис файлу краще робити щоразу після успішної зміни даних. Ви можете це зробити окремою функцією (без перевірки `if initial_records != len(phone_book)` і викликати цю функцію в 2х місцях: між рядками 45 і 46 та між рядками 59 і 60

2023-04-12 10:14 UTC, Karolina777 commented on 12/hmw-12-01.py
> +if initial_records != len(phone_book):
дякую за коментар, так дійсно практичніше в роботі. змінила

2023-04-20 19:06 UTC, klymenok approved these changes
Looks good!

2023-04-20 19:39 UTC, merged