homework 14
Karolina777/robotdreams-python pull request #9
Opened 2023-04-10 10:17 UTC by Karolina777

please, review my homework to the 14th lesson

2023-04-10 13:12 UTC, klymenok requested changes

2023-04-10 13:12 UTC, klymenok commented on 14/hmw-14-01.py
> +while True:
Тут має бути код із телефонною книгою, що реалізована в завданні 07. У вас частини того коду не вистачає

2023-04-10 13:12 UTC, klymenok commented on 14/hmw-14-01.py
> +phone_number_pattern = r"^(?:\+?38)?(?:0|\(0\))?\d{9}$"
Ваш патерн пропускає деякі невалідні формати номерів, такі як:
```
095123456
38095123456
```

2023-04-11 18:24 UTC, Karolina777 commented on 14/hmw-14-01.py
> +phone_number_pattern = r"^(?:\+?38)?(?:0|\(0\))?\d{9}$"
Hi, I have tested and changed the pattern. Please, review

2023-04-20 19:22 UTC, klymenok requested changes

2023-04-20 19:22 UTC, klymenok commented on 14/hmw-14-01.py
> +while True:
@Karolina777 у вас тут 2 реалізації телефонної книги. Видаліть зайву – код із 14 по 46 рядок.

Для ініціалізації телефонної книги зробіть наступне:
1. Спробуйте відкрити файл із телефонної книги, прочитати його, трансформувати в dict за допомогою бібліотеки json і записати вміст в `phone_book`
2. Якщо файлу не існує – створіть пустий dict `phone_book`, а файл створиться при першому записі в нього

2023-05-08 21:34 UTC, Karolina777 commented on 14/hmw-14-01.py
> +while True:
I have made the changes and committed. Please, review

2023-05-11 13:11 UTC, klymenok approved these changes

2023-05-13 12:59 UTC, merged